"""add deleted_at column for soft delete

Revision ID: 3ecd010f5e28
Revises: 0993a8d58d26
Create Date: 2026-08-28 21:40:58.029916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ecd010f5e28'
down_revision = '0993a8d58d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('categories_category_name_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_categories_category_name'), ['category_name'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('products_sku_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_products_sku'), ['sku'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('users_email_key', type_='unique')
        batch_op.drop_constraint('users_username_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.create_unique_constraint('users_username_key', ['username'])
        batch_op.create_unique_constraint('users_email_key', ['email'])
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_products_sku'), type_='unique')
        batch_op.create_unique_constraint('products_sku_key', ['sku'])
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_categories_category_name'), type_='unique')
        batch_op.create_unique_constraint('categories_category_name_key', ['category_name'])
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
